-- Naam student: 
--
-- Status implementatie: 
--
-- Te raadplegen tabellen: results en races
--
-- Beperkingen:
--      - de oplossing moet bestaan uit één enkele SQL opdracht, eventueel
--        voorafgegaan door CTE's. het gebruik van PL/SQL is niet toegelaten
--      - samengestelde opdrachten (UNION, ...) zijn niet toegelaten
--      - gecorreleerde subqueries zijn niet toegelaten
--      - recursieve (hiërarchische) queries zijn niet toegelaten
--      - je mag enkel de standaard beschikbare vormen van analytische functies
--        (de van aggregaatsfuncties afgeleide reportingfuncties, en de ranking-
--        functies row_number, rank, dense_rank en ntile) gebruiken, niet de
--        Oracle-specifieke vormen ervan (zoals windowing of top clausules, lag,
--        lead, first, first_value, ...)
--      - je mag geen gebruik maken van pseudokolommen zoals ROWNUM of ROWID.
--
-- kolom 2 en kolom 3 bevat respectievelijk de top drie skiërs en skiesters
-- kolom 4 en kolom 5 bevat respectievelijk de top zeven skiërs en skiesters (die niet tot de top 3 behoren)
-- kolom 6 en kolom 7 bevat respectievelijk de top 10skiërs en skiesters (die niet tot de top 3 of 7 behoren)